### ISSUE TITLE
About the API

### ISSUE THREAD

**Issue by zchrissirhcz** [jobtalle/pool#7]
Hi, thanks for sharing this repo.  I read the code and just don't understand this API:

https://github.com/jobtalle/pool/blob/05b7492462528f75cd7b17bc99a6fc6be0fd19ef/pool.h#L25
```c++
void *poolMalloc(pool *p);
```

What I expect is something like:
```c++
void* poolMalloc(pool*p, size_t size);
```
which can be called, as replacement of malloc like this:
```c++
int* data = (int*)malloc(100*sizeof(int)); // before
int* data = (int*)poolMalloc(p, 100*sizeof(int)); // after
```

**Comment by jobtalle** [comment]
This pool only allows for allocations that all have the same predefined size, so you could use it for storing a number of structs of a certain type, but not for storing things of arbitrary size. For that, you'd need a more sophisticated pool.
